name: Release


on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN_CAROLYN }}

    # - name: Parse version info from lib-version
    #   run: |
    #     VERSION=${GITHUB_REF:11}
    #     MAJOR=$(echo "$VERSION" | cut -d . -f 1)
    #     MINOR=$(echo "$VERSION" | cut -d . -f 2)
    #     PATCH=$(echo "$VERSION" | cut -d . -f 3)
    #     echo "version=$VERSION" >> $GITHUB_ENV
    #     echo "version_major=$MAJOR" >> $GITHUB_ENV
    #     echo "version_minor=$MINOR" >> $GITHUB_ENV
    #     echo "version_patch=$PATCH" >> $GITHUB_ENV

    - name: Parse version info from pom.xml
      run: |
        echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/doda2025-team3/app
        tags: |
          type=raw, value=${{ env.VERSION }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image to registry
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # - name: Build and push image to registry
    #   uses: docker/build-push-action@v6
    #   with:
    #     platforms: linux/amd64,linux/arm64
    #     context: .
    #     push: true
    #     tags: |
    #       ghcr.io/doda2025-team3/app:${{ env.version }}
    #       ghcr.io/doda2025-team3/app:${{ env.version_major }}.${{ env.version_minor }}.latest
    #       ghcr.io/doda2025-team3/app:${{ env.version_major }}.latest
    #       ghcr.io/doda2025-team3/app:latest

   # - name: Build and push image to registry (this is from the in-class assignment)
   #   run: |
   #     IMG="ghcr.io/${{github.repository}}"
   #     IMG=${IMG@L} # lower case the image
   #     docker build \
   #       --tag $IMG:${{ env.version }} \
   #       --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
   #       --tag $IMG:${{ env.version_major }}.latest \
   #       --tag $IMG:latest \
   #       
   #     docker push --all-tags $IMG